volumes:
  db-data:

services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    env_file:
      - .env.development
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - .env.development
    tty: true
    ports:
      - "8080:8080"
    working_dir: /var/www/
    volumes:
      - ./app:/var/www/
    depends_on:
      - db

  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - 8081:8080
    depends_on:
      - db
